package Configuracion;
// Generated 11/10/2023 07:53:19 PM by Hibernate Tools 4.3.1



/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private int ICateogoria;
     private String nombre;
     private String fecha;

    public Categoria() {
    }

	
    public Categoria(int ICateogoria) {
        this.ICateogoria = ICateogoria;
    }
    public Categoria(int ICateogoria, String nombre, String fecha) {
       this.ICateogoria = ICateogoria;
       this.nombre = nombre;
       this.fecha = fecha;
    }
   
    public int getICateogoria() {
        return this.ICateogoria;
    }
    
    public void setICateogoria(int ICateogoria) {
        this.ICateogoria = ICateogoria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }




}


